### ISSUE TITLE
Error upon loading, following readme.md

### ISSUE THREAD

**Issue by bramnet** [mam91/Neat-Genetic-Mario#4]
When loading the script, the console instantly outputs:
could not find file: C:/Users/mmill/Downloads/BizHawk-2.2/Lua/SNES/neat-mario/pool/DP1.state
NLua.Exceptions.LuaScriptException: [string "main"]:850: attempt to index local 'file' (a nil value)

I'm sure this is something I can adjust in the config settings, just thought you might want to update the readme.md file.

**Comment by wts42** [comment]
Strange I will go over it and clone your repo tomorrow and check where the bug is. I have already done some more additions but will send you a pull of all together when it is done. I will also revert the Readme so it doesn't conflict with your version for the pull req. Wish you a nice evening from Germany. 



Am 12. April 2018 00:31:32 MESZ schrieb bramnet <notifications@github.com>:
>When loading the script, the console instantly outputs:
>could not find file:
>C:/Users/mmill/Downloads/BizHawk-2.2/Lua/SNES/neat-mario/pool/DP1.state
>NLua.Exceptions.LuaScriptException: [string "main"]:850: attempt to
>index local 'file' (a nil value)
>
>I'm sure this is something I can adjust in the config settings, just
>thought you might want to update the readme.md file.

**Comment by bramnet** [comment]
After adjusting small sections of config.lua and mario-neat.lua, I was able to get it to work. The only main issue was that it was trying to point to a file that doesn't exist. Specifically on C:/Users/mmill/Downloads/BizHawk-2.2/Lua/SNES/neat-mario/pool/DP1.state... as I don't have any users named mmill, I can only assume this was left over from developing.

**Comment by wts42** [comment]
I was already sweating because of not finding the bug. Did suppose it was some weird Lua behavior I was not aware of. So first ticket closed :)

**Comment by wts42** [comment]
Which section in mario-neat.lua did you change? Shouldn't be needed if config has correct path. BR

**Comment by wts42** [comment]
I just have seen that you meant the old version. A pull request which fixes the problems you mentioned is already out but not yet merged with the main repository. Also the Readme got updated and some other changes were made. (like include power ups in fitness calc or distinguish between good and bad sprites)

**Comment by mam91** [comment]
Sorry guys I haven't kept up with this project.  I'm merging wts changes now.

**Comment by bramnet** [comment]
Sorry for taking so long. 
I had to change mario-neat.lua line 972 and config.lua line 5

**Comment by wts42** [comment]
Ah, I know this one. Was with the old version. Have you checked the actual version? Maintainer merged my pull request. So new howto is in Readme. After downloading you should only need to adjust one path in configuration and it should be up and running. BR

**Comment by wts42** [comment]
Ah, I know this one. Was with the old version. Have you checked the actual version? Maintainer merged my pull request. So new howto is in Readme. After downloading you should only need to adjust one path in configuration and it should be up and running. BR

**Comment by wts42** [comment]
Ah, I know this one. Was with the old version. Have you checked the actual version? Maintainer merged my pull request. So new howto is in Readme. After downloading you should only need to adjust one path in configuration and it should be up and running. BR

**Comment by wts42** [comment]
Ah, I know this one. Was with the old version. Have you checked the actual version? Maintainer merged my pull request. So new howto is in Readme. After downloading you should only need to adjust one path in configuration and it should be up and running. BR

**Comment by bramnet** [comment]
Well, keep in mind that I reported this 11 days ago. It looks like the readme was only updated 4 days ago. Still, glad to see that the issue was resolved.

**Comment by wts42** [comment]
I know, it wasn't intended as blame but to make you aware of the changes. :) I am currently searching for a way to detect scrolling in ram. If anyone has a clue for me this would be very helpful. BR
